# Generated by Django 4.0.5 on 2022-07-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
